// Маппинг названий файлов (на русском) на ключи локализации
const Map<String, String> animalNameKeys = {
  // Pets
  'Канарейка': 'animal_canary',
  'Капибара': 'animal_kapibara',
  'Карликовый кролик': 'animal_dwarf_rabbit',
  'Кошка': 'animal_cat',
  'Лягушка': 'animal_frog',
  'Морская свинка': 'animal_guinea_pig',
  'Паук-птицеед': 'animal_tarantula',
  'Попугай': 'animal_parrot',
  'Рыбка': 'animal_fish',
  'Собака': 'animal_dog',
  'Улитка': 'animal_snail',
  'Хомяк': 'animal_hamster',
  'Хорек': 'animal_ferret',
  'Черепаха': 'animal_turtle',
  'Шиншилла': 'animal_chinchilla',
  'Ящерица': 'animal_lizard',
  
  // Farm Animals
  'Баран': 'animal_ram',
  'Бык': 'animal_bull',
  'Гусь': 'animal_goose',
  'Индюк': 'animal_turkey',
  'Коза': 'animal_goat',
  'Корова': 'animal_cow',
  'Курица': 'animal_chicken',
  'Лошадь': 'animal_horse',
  'Овца': 'animal_sheep',
  'Осел': 'animal_donkey',
  'Петух': 'animal_rooster',
  'Свинья': 'animal_pig',
  'Утка': 'animal_duck',
  'Фазан': 'animal_pheasant',
  
  // Wild Animals Russia
  'Белка': 'animal_squirrel',
  'Белый медведь': 'animal_polar_bear',
  'Бурый медведь': 'animal_brown_bear',
  'Волк': 'animal_wolf',
  'Горностай': 'animal_stoat',
  'Заяц-беляк': 'animal_snowshoe_hare',
  'Заяц-русак': 'animal_european_hare',
  'Кабан': 'animal_wild_boar',
  'Косуля': 'animal_roe_deer',
  'Лисица': 'animal_fox',
  'Лось': 'animal_moose',
  'Морж': 'animal_walrus',
  'Рысь': 'animal_lynx',
  'Северный олень': 'animal_reindeer',
  'Суслик': 'animal_ground_squirrel',
  'Тигр амурский': 'animal_siberian_tiger',
  
  // African Animals
  'Бегемот': 'animal_hippo',
  'Буйвол': 'animal_buffalo',
  'Верблюд': 'animal_camel',
  'Гепард': 'animal_cheetah',
  'Гиена': 'animal_hyena',
  'Горилла': 'animal_gorilla',
  'Зебра': 'animal_zebra',
  'Крокодил': 'animal_crocodile',
  'Лев': 'animal_lion',
  'Лемур': 'animal_lemur',
  'Леопард': 'animal_leopard',
  'Носорог': 'animal_rhino',
  'Слон': 'animal_elephant',
  'Страус': 'animal_ostrich',
  'Сурикат': 'animal_meerkat',
  'Шимпанзе': 'animal_chimpanzee',
};
